language: python

python:
  - "3.6"
  
script:
  - python -m unittest discover

branches:
  only:
    - master     
 
deploy:
 provider: pages
 skip-cleanup: true
 github-token: $GITHUB_TOKEN$
 keep-history: true
 on:
   branch: master
    
notifications:
  email:
    recipients:
      - 13672451429@163.com
      - 845722463@qq.com
    on_success: change # default: change
    on_failure: always # default: always
 
env:
  global:
    # 我将其添加到了travis-ci的环境变量中
  
addons:
  apt:
    update: true
      