language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install coveralls
script:
  - coverage run --source=. -m unittest discover

branches:
  only:
    - master     
 
after_script:
  - cd ./public
  - git init
  - git config user.name "${U_NAME}"
  - git config user.email "${U_EMAIL}"
  - git add .
  - git commit -m "Update microblog"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GITHUB_REF}" master:${P_BRANCH} 

after_success:
  - coveralls
  
notifications:
  email:
    recipients:
      - 13672451429@163.com
      - 845722463@qq.com
    on_success: change # default: change
    on_failure: always # default: always
 
env:
  global:
    # 我将其添加到了travis-ci的环境变量中
  
addons:
  apt:
    update: true
      